apiVersion: v1
kind: Secret
metadata:
  name: payment-db-secret
  namespace: ride-hailing
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  namespace: ride-hailing
data:
  DRIVER_SERVICE_URL: http://driver-service:3003
  PAYMENT_SERVICE_URL: http://payment-service:8082
  TRIP_SERVICE_URL: http://trip-service:3002/v1/trips
  VROOM_GATEWAY_URL: http://vroom-gateway:8080
