apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: driver-sqlite-pvc
  namespace: ride-hailing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trip-sqlite-pvc
  namespace: ride-hailing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-postgres-pvc
  namespace: ride-hailing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
