apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-postgres
  namespace: ride-hailing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-postgres
  template:
    metadata:
      labels:
        app: payment-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: paymentdb
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: payment-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: payment-postgres-data
          persistentVolumeClaim:
            claimName: payment-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: payment-postgres
  namespace: ride-hailing
spec:
  type: ClusterIP
  selector:
    app: payment-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
